// projectsData.js
const projectsData = {
    Cloud: [
      { title: "Site estático na S3", 
        tags: ["AWS"], 
        description: "Hospedando site estático no S3 da AWS", 
        site: "", 
        repo: "", 
        article:"https://medium.com/@eduardolentz/como-hospedei-minha-landing-page-profissional-na-aws-s3-um-guia-passo-a-passo-fc33b9ebc454" },
    ],
    DevOps: [
      { title: "Projeto CI/CD GitHub Actions", 
        tags: ["CI/CD","AWS"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"https://medium.com/@eduardolentz/como-automatizei-o-deploy-do-meu-site-est%C3%A1tico-na-aws-s3-com-github-actions-03417f871227" },
    ],
    Python: [
      { title: "Exercícios Python ", 
        tags: [""], 
        description: "Exercícios e desafios do curso do André Iacono", 
        site: "", 
        repo: "https://github.com/eduardolentz/python-udemy-andreiacono", 
        article:"" },
      { title: "Projeto API Python ", 
        tags: ["FastAPI","Docker"], 
        description: "API em Python com PostgreSQL e Docker.", 
        site: "", 
        repo: "https://github.com/eduardolentz/API-python-biblioteca", 
        article:"https://medium.com/@eduardolentz/construindo-tr%C3%AAs-apis-em-um-final-de-semana-net-python-e-node-js-22a473e4f8df" },  
    ],
    JavaScript: [
      { title: "Projeto API Node.js", 
        tags: ["Node.js"], 
        description: "API em Node com PostgreSQL e teste", 
        site: "", 
        repo: "https://github.com/eduardolentz/API-node-biblioteca", 
        article:"https://medium.com/@eduardolentz/construindo-tr%C3%AAs-apis-em-um-final-de-semana-net-python-e-node-js-22a473e4f8df" },
    ],
    dotnet: [
      { title: "Projeto API .NET", 
        tags: [".NET",], 
        description: "API em .NET 8 com PostgreSQL e Docker.", 
        site: "", 
        repo: "https://github.com/eduardolentz/API-dotnet-biblioteca", 
        article:"https://medium.com/@eduardolentz/construindo-tr%C3%AAs-apis-em-um-final-de-semana-net-python-e-node-js-22a473e4f8df" },
    ],  
    Java: [
      { title: "Projeto API Spring Boot", 
        tags: ["Spring Boot"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"" },
    ],  
    Dados: [
      { title: "MinhaBibliotecaDB", 
        tags: ["NoSQL"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"" },
    ],
    FrontEnd: [
      { title: "Web site portifólio", 
        tags: ["html+css+js"], 
        description: "Landing page interativa para apresentar meu currículo e projetos", 
        site: "", 
        repo: "https://github.com/eduardolentz/website-eduardolentz", 
        article:"",
        doc:""},
    ],
    Outros: [
      { title: "Projeto API Go", 
        tags: ["Go"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"" },
    ],
    Artigos: [
      { title: "Preparação AWS Cloud Practitioner", 
        tags: ["Certificações"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"" },
      { title: "Desafio três APIs, 3 linguagens. V.1", 
        tags: ["Projetos"], 
        description: "APIs em .Net, Python, Node.js", 
        site: "", 
        repo: "", 
        article:"https://medium.com/@eduardolentz/construindo-tr%C3%AAs-apis-em-um-final-de-semana-net-python-e-node-js-22a473e4f8df" },
      { title: "Preparação AWS Solutions Architect - Associate", 
        tags: ["Certificações"], 
        description: "Em construção", 
        site: "", 
        repo: "", 
        article:"" },
      { title: "Desafio três APIs, 3 linguagens. V.2", 
        tags: ["Projetos"], 
        description: "APIs em Java, Typescript, Go. Em construção", 
        site: "", 
        repo: "", 
        article:"" },
    ],    
  };
  